export const NANOSECONDS_IN_ONE_MICROSECOND = 1000n
export const NANOSECONDS_IN_ONE_MILLISECOND = NANOSECONDS_IN_ONE_MICROSECOND * 1000n
export const NANOSECONDS_IN_ONE_SECOND = NANOSECONDS_IN_ONE_MILLISECOND * 1000n
export const NANOSECONDS_IN_ONE_MINUTE = NANOSECONDS_IN_ONE_SECOND * 60n
export const NANOSECONDS_IN_ONE_HOUR = NANOSECONDS_IN_ONE_MINUTE * 60n
export const NANOSECONDS_IN_ONE_DAY = NANOSECONDS_IN_ONE_HOUR * 24n

const UNIT_NANOSECOND = 'ns'
const UNIT_MICROSECOND = 'μs'
const UNIT_MILLISECOND = 'ms'
const UNIT_SECOND = 's'
const UNIT_MINUTE = 'm'
const UNIT_HOUR = 'h'
const UNIT_DAY = 'd'

export default {
  NANOSECONDS_IN_ONE_MICROSECOND,
  NANOSECONDS_IN_ONE_MILLISECOND,
  NANOSECONDS_IN_ONE_SECOND,
  NANOSECONDS_IN_ONE_MINUTE,
  NANOSECONDS_IN_ONE_HOUR,
  NANOSECONDS_IN_ONE_DAY,
  UNIT_NANOSECOND,
  UNIT_MICROSECOND,
  UNIT_MILLISECOND,
  UNIT_SECOND,
  UNIT_MINUTE,
  UNIT_HOUR,
  UNIT_DAY
}
